language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
- which cargo-make || cargo install cargo-make

script:
- cargo make ci-flow
- cargo make format-flow

notifications:
  email:
    on_success: never
