language: rust
deploy:
  provider: cargo
  token:
    secure: kh2xYURp1SiDLBB6qn1hXfxlFesInLuY13D8NGU7E63XqoGhXk7HLsh9gWb2MVp1GlxkTEe34ZF478HRlvyw/OVIPpXh4lwGDFyhooODojYBBDsddk2xMWRHuwpgOnXs24LeIiZHz8LPDP/47LU0B9/MibaFOv7QaWEcgN6Vplb4xCRijwr0ZkdR82/oxDwKmPzcUDt1yMpikzqablkMWWHduDyENTCX2bNe6cam6KvK6yGeLYDiRcpN75VTHOAeFFXwwxPuHV6GPMFnvQIW1vlDiHqkQkVrjLJJ5u0th4ZAWhkrJjH6jAfJNDuz0DwSqPQ/f1GrNEBzU5QU0i8LVsFlKimhBJiWZh0lb7kMgWS4s1tJB6rzaERbLBdx4L40YrbFyQNqh/QQQCIGuCkOFq372t3rpfJcSPOqqDXxEncADOP4vsxJgDIcS9T9LrvpBFuxe2c0Dr/vCrrG25TgzVLVxaqIGefOxfcOXty+0gwKdWZRA6Acp3ePC4huLdMcjWfpS6DA72QYeOcq9xXMlYIMIyRa/KTS/YcNVn9a1dgQC8aMjnIwA0zLpv/FGGSTUfFdQuQpsqWnW38rX19PWuLJz1z5xtcUHEmWPzS/0Rm0hmCjXAPb3tw4TW35ODjz8qZy4ZOj6e4uJYXMRohLPrWlU+LhCFjVF6l2AczRYpQ=
  on:
    tags: true

env:
  global:
  - CARGO_FEATURES="--no-default-features"

rust:
- 1.31.0
- stable
- beta
- nightly

before_script:
- which cargo-make || cargo install cargo-make
- echo CARGO_FEATURES="${CARGO_FEATURES}" > /tmp/ci.env
- cat /tmp/ci.env

script:
- cargo make --env-file=/tmp/ci.env ci-flow

stages:
- check
- test
- test_features
- format

jobs:
  fast_finish: true
  allow_failures:
  - rust: nightly
  include:
  - stage: check
    rust: stable
    script: cargo check
  - stage: check
    rust: 1.31.0
    script: cargo check
  - stage: test_features
    rust: nightly
    env: CARGO_FEATURES="--all-features"
    script: cargo make --env-file=/tmp/ci.env ci-flow
  - stage: format
    rust: nightly
    script: cargo make format-flow

cache:
  cargo: true

notifications:
  email:
    on_success: never
