language: rust
env:
  global:
    - CARGO_FEATURES="--no-default-features"

rust:
  - 1.31.0
  - stable
  - beta
  - nightly

before_script:
  - which cargo-make || cargo install cargo-make
  - echo CARGO_FEATURES="${CARGO_FEATURES}" > /tmp/ci.env
  - cat /tmp/ci.env

script:
  - cargo make --env-file=/tmp/ci.env ci-flow

stages:
  - check
  - test
  - test_features
  - format
  - name: deploy
    if: tag IS present

jobs:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - &check
      stage: check
      rust: stable
      script: cargo check
    - <<: *check
      rust: 1.31.0
    - stage: test_features
      rust: nightly
      env: CARGO_FEATURES="--all-features"
      script: cargo make --env-file=/tmp/ci.env ci-flow
    - stage: format
      rust: nightly
      script: cargo make format-flow
    - stage: deploy
      rust: stable
      script: cargo make publish-flow

cache:
  cargo: true

notifications:
  email:
    on_success: never
