language: rust
rust:
  - 1.31.0
  - stable
  - beta
  - nightly

before_script:
  - which cargo-make || cargo install cargo-make

script:
  - cargo make ci-flow
  - cargo make format-flow

stages:
  - check
  - test
  - name: deploy
    if: tag IS present

jobs:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - &check
      stage: check
      rust: stable
      script: cargo check --all-targets
    - <<: *check
      rust: 1.31.0
    - stage: deploy
      rust: stable
      script: cargo make publish-flow

notifications:
  email:
    on_success: never
